### ISSUE TITLE
[질문] 현재 백엔드 진행 상황 

### ISSUE THREAD

**Issue by KanuKim97** [Team-Crackdown/TAVE-Backend#1]
**질문 사항**
현재 백엔드 진행 상황에 대한 공유의 건으로 Issue남깁니다.
제 질문 사항입니다.
1. 현재 작업이 어디까지 진행되었는지?
2. Android 클라이언트 연동을 위한 API 작업은 어느 정도의 진척이 있는지?
3. 2번 사항이 불 충분 된다면 기간은 얼마나 더 소요되는지?
4. 만약 2번이 어느정도 진척 사항이 있다면 Test용으로 따로 Release 가능한 상태인지? 

에 대하여 답변 주시면 감사하겠습니다.

**추신**
같이 작업 중인 @Luna828 님께도 설명드릴 예정입니다! 
되도록 쉽게 설명 해주시면 감사하겠습니다!
빠른 답변 기다리겠습니다! @Kimhojoon1 @KOOJAESUNG @githyuniiee !

**Comment by KOOJAESUNG** [comment]
1. 현재 기본적인 crud에 대한 컨트롤러까지 작성 완료, sms, otp인증 모듈 구현 완료, sse 모듈 작성 완료하였고 적절한 api 추가, s3 연결, nginx+TLS+도메인 발급+로드밸런싱+포트포워딩, spring security 적용해야 합니다

2. api작업은 금일부터 시작할 예정이며, 우선 백엔드에서 필요해보이는 것 위주로 작성 후 토요일 회의를 통해 추가할 api를 토의할 예정입니다

3. spring security 적용 후 바로 작성할 예정이며, 일요일까지 가능할 것으로 보입니다

4. 추가적으로 테스트 후 수정이 필요한 관계로 일요일까지 테스트 가능하도록 릴리즈할 예정입니다

**Comment by KanuKim97** [comment]
> 1. 현재 기본적인 crud에 대한 컨트롤러까지 작성 완료, sms, otp인증 모듈 구현 완료, sse 모듈 작성 완료하였고 적절한 api 추가, s3 연결, nginx+TLS+도메인 발급+로드밸런싱+포트포워딩, spring security 적용해야 합니다
> 
>     2. api작업은 금일부터 시작할 예정이며, 우선 백엔드에서 필요해보이는 것 위주로 작성 후 토요일 회의를 통해 추가할 api를 토의할 예정입니다
> 
>     3. spring security 적용 후 바로 작성할 예정이며, 일요일까지 가능할 것으로 보입니다
> 
>     4. 추가적으로 테스트 후 수정이 필요한 관계로 일요일까지 테스트 가능하도록 릴리즈할 예정입니다

넵 답변 감사합니다 @KOOJAESUNG 
@KOOJAESUNG 님이 잘 설명해 주셔서 이 Issue는 바로 Close 하겠습니다!
