### ISSUE TITLE
[질문 & 답변 요청] TAVE Notice 관련 기능 질문

### ISSUE THREAD

**Issue by KanuKim97** [Team-Crackdown/TAVE-Backend#4]
**질문 사항**
안녕하세요 @githyuniiee , @KOOJAESUNG ! 
안드로이드 개발을 하고 있는 와중에 궁금한 점이 있어 질문 드립니다!
1. /notice/sse-connect/{client_id}와 /notice/getnotice의 차이가 무엇인지 궁금합니다!
2. /notice/sse-connect/{client_id}는 SSE를 통해 동작한다고 되어있습니다. 하지만 제가 간단한 클라이언트 프로그램을 제작해 사용해 본 결과 SSE 연결이 정상적으로 이루어 지지 않습니다!
3. 2번 사항에 대해 참고할 만한 레퍼런스가 있을까요?
4. SSE를 통해 구독 받는 것은 Notice에 대한 정보여야 하는 것으로 알고 있습니다. 그런데 왜  API Docs에서 Responses는 "timeout"만 존재하는 걸까요? 
5. 만약 timeout를 사용하신 의도가 서버 단의 자원소모를 막기 위함이라면 클라이언트에서 SSE 통신을 close()하는 것으로 해결이 가능하지 않을까요? 이 코드를 작성하신 의도가 궁금합니다.

**추신**
@KOOJAESUNG , @githyuniiee 빠른 답변 주시면 감사하겠습니다!
충분한 답변과 레퍼런스가 체크되기 전 까지는 클라이언트에서 SSE를 연결하는 작업은 Hold 하겠습니다.

**Comment by KOOJAESUNG** [comment]
1. /notice/sse-connect/{client_id}는 Member의 id를 파라미터로 SSE를 통한 알림 서비스에 등록하는 것이고, /notice/getnotice는 Notice의 id를 파라미터로 해당 Notice를 호출하는 API입니다. /notice/sse-connect/{client_id}같은 경우 SSE에 대해 별도로 컨트롤러를 작성할 예정이므로 현재는 테스트를 위해 사용해주시면 됩니다.
2. @githyuniiee 답변해주시면 감사하겠습니다
3. @githyuniiee 답변해주시면 감사하겠습니다
4. 현재 develop branch에서는 구독한 Member의 id를 리스트로 리턴하는 것으로 수정되었습니다. 1번, 2번 문제가 해결된 후 release하도록 하겠습니다.
5. 현재 인지하고 있는 문제이며, 그에 따라 develop branch에서는 4번과 같이 수정했습니다. 자원소모 문제는 사용자의 로그아웃시 SSE통신을 해제하면 해결될 것으로 보입니다.

**Comment by githyuniiee** [comment]
2. SSE 기능 관련 부분은 현재 수정 중이며, 가능한 빠르게 업데이트하도록 하겠습니다. 
3. 참고하시면 좋을 것 같습니다.
https://tecoble.techcourse.co.kr/post/2022-10-11-server-sent-events/
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

**Comment by KanuKim97** [comment]
넵 ! 전부 확인했습니다! Issue Close 하겠습니다!
@KOOJAESUNG , @githyuniiee 님 답변 주셔서 감사합니다 :)
