### ISSUE TITLE
[버그] Server-Sent-Event Client 연결 시 Timeout Exception 발생

### ISSUE THREAD

**Issue by KanuKim97** [Team-Crackdown/TAVE-Backend#7]
안녕하세요! @githyuniiee
늦은 시간에 이렇게 이슈 남깁니다!
 
**어떤 문제를 겪고 있는지**
Swagger에서 Test한 결과와 반대로 Client에서 SSE Endpoint에 연결을 요청하면 지속적으로 Timeout Exception이 발생합니다!
@githyuniiee 님께서 하신 SSE Test 는 이상이 없었다고 하셨지만 현재 클라이언트에서 Timeout Exception이 발생하는 관계로 SSE에 대한 더 정밀한 테스트가 필요할 거 같습니다!
아래 Client연결 결과와 Swagger에서 사용한 결과를 이미지로 같이 첨부하겠습니다!

**이미지**
> ![image](https://github.com/Team-Crackdown/TAVE-Backend/assets/74421057/d1036e8e-2c67-445d-9c82-a145d0d4cb17)
> Swagger를 이용한 테스트 결과 -> 200 Code
> 
> ![image](https://github.com/Team-Crackdown/TAVE-Backend/assets/74421057/0d43f0a3-d6cc-42fd-a61b-429ba9137f53)
> Postman을 이용한 테스트 결과-> Timeout
>
> ![image](https://github.com/Team-Crackdown/TAVE-Backend/assets/74421057/9ff32c5b-d8eb-42b1-94a0-31204e754cdc)
> Android Client를 통한 테스트 결과 -> Timeout

**추신**
확인 후 현재 진행 상황과 관련된 간단한 Comment 해주시면 감사하겠습니다! @githyuniiee

**Comment by githyuniiee** [comment]
Timeout Exception 확인하였으며, 우선 Sse 타임 아웃을 무제한으로 수정하였습니다. 
조금 더 정밀한 테스트 후 다시 업데이트하도록 하겠습니다.

**Comment by KanuKim97** [comment]
![image](https://github.com/Team-Crackdown/TAVE-Backend/assets/74421057/26caa82c-4e6a-4a39-bcb0-ff7067837e0d)
이슈 해결완료로 인한 Close
